#pragma once

#define OPENM5KIT_DASHBOARD_ENABLED false

#define OPENM5KIT_WIFI_SSID "YOUR_WIFI_SSID"
#define OPENM5KIT_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

// Use your computer's LAN IP, not localhost. Example: http://192.168.1.25:3000
#define OPENM5KIT_DASHBOARD_BASE_URL "http://YOUR_DASHBOARD_IP:3000"

#define OPENM5KIT_DEVICE_ID "cores3-dev-001"
#define OPENM5KIT_PAIRING_CODE "482913"
#define OPENM5KIT_FIRMWARE_VERSION "0.1.0"

#define OPENM5KIT_HELLO_INTERVAL_MS 30000
#define OPENM5KIT_EVENT_INTERVAL_MS 5000
#define OPENM5KIT_MESSAGE_INTERVAL_MS 3000
#define OPENM5KIT_SCREEN_TIMEOUT_MS 60000
